from django.urls import path
from . import views

urlpatterns = [
    path('', views.loginPage, name="Login"),
    path('home', views.home, name="Home"),
    path('studenthome', views.studentHome, name="StudentHome"),
    path('memberhome', views.memberHome, name="MemberHome"),
    path('universityhome', views.universityHome, name="UniversityHome"),
    path('departmentHome', views.departmentHome, name="DepartmentHome"),
    path('updatedept', views.updateDept, name="UpdateDept"),
    path('signupstudent', views.studentSignupPage, name="StudentSignup"),
    path('signupmember', views.memberSignupPage, name="MemberSignup"),
    path('signupdepartment', views.departmentSignupPage, name="DepartmentSignup"),
    path('signupuniversity', views.universitySignupPage, name="UniversitySignup"),
    path('handlestudentsignup', views.handleStudentSignup, name="HandleStudentSignup"),
    path('handlemembersignup', views.handleMemberSignup, name="HandleMemberSignup"),
    path('handleuniversitysignup', views.handleUniversitySignup, name="HandleUniversitySignup"),
    path('handledepartmentsignup', views.handleDepartmentSignup, name="HandleDepartmentSignup"),
    path('handlestudentlogin', views.handleStudentLogin, name="handleStudentLogin"),
    path('handlememberlogin', views.handleMemberLogin, name="handleMemberLogin"),
    path('handleuniversitylogin', views.handleUniversityLogin, name="HandleUniversityLogin"),
    path('handledepartmentlogin', views.handleDepartmentLogin, name="HandleDepartmentLogin"),
    path('login', views.handleLogin, name="HandleLogin"),
    path('logout', views.handleLogout, name="HandleLogout"),
    path('studenthome/logout', views.handleStudentLogout, name="HandleStudentLogout"),
    path('memberhome/logout', views.handleMemberLogout, name="HandleMemberLogout"),
    path('universityhome/logout', views.handleUniversityLogout, name="HandleUniversityLogout"),
    path('departmenthome/logout', views.handleDepartmentLogout, name="HandleDepartmentLogout"),
    path('studentlogin', views.studentLoginPage, name="StudentLogin"),
    path('memberlogin', views.memberLoginPage, name="MemberLogin"),
    path('universitylogin', views.universityLoginPage, name="UniversityLogin"),
    path('departmentlogin', views.departmentLoginPage, name="DepartmentLogin"),
    path('addquery', views.addQuery, name="AddQuery"),
    path('handledeletedept', views.handleDeleteDept, name="HandleDeleteDept"),
    path('handleupdatedept', views.handleUpdateDept, name="HandleUpdateDept"),
    path('handledeleteuni', views.handleDeleteUni, name="HandleDeleteUni"),
    path('handleupdateuni', views.handleUpdateUni, name="HandleUpdateUni"),
    path('handledeletemember', views.handledDeleteMember, name="HandledDeleteMember"),
    path('updatedept', views.UpdateDept, name="UpdateDept"),
    path('updateuni', views.updateUni, name="updateUni"),
    path('queryhistory', views.queryHistory, name="queryHistory"),
    path('querydepthistory', views.quieryDeptHisotry, name="QuieryDeptHisotry"),
    path('invalidquery', views.invalidQuery, name="InvalidQuery"),
    path('invaliddeptquery', views.invalidDepartmentQuery, name="InvalidDepartmentQuery"),
    path('sendmessage', views.sendMessage, name="SendMessage"),
    path('handlesendmessage', views.handleSendMessage, name="HandleSendMessage"),
    
]
