# Generated by Django 3.2.7 on 2021-09-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_queryhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryhistory',
            name='response',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
