# Generated by Django 3.2.7 on 2021-09-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0006_queryhistory_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_department',
            field=models.BooleanField(default=False),
        ),
    ]
