# Generated by Django 3.2.7 on 2021-09-18 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0008_admindept'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admindept',
            old_name='admin_user',
            new_name='admin',
        ),
    ]
