# Generated by Django 3.2.7 on 2021-09-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0011_auto_20210918_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='deptuni',
            name='username',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
