# Generated by Django 3.2.7 on 2021-09-18 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0013_studentuni'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentUni',
        ),
    ]
