# Generated by Django 3.2.7 on 2021-09-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0014_delete_studentuni'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryhistory',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
