# Generated by Django 3.2.7 on 2021-09-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0017_studentuni'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=255)),
            ],
        ),
    ]
