# Generated by Django 3.2.7 on 2021-09-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0018_schedulemsg'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulemsg',
            name='msg',
            field=models.CharField(default='This message is empty', max_length=255),
        ),
    ]
