# Generated by Django 3.2.7 on 2021-09-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0020_studentuni_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuni',
            name='number',
            field=models.CharField(default='+920000000000', max_length=255),
        ),
    ]
