# Generated by Django 3.2.7 on 2021-09-20 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0022_alter_studentuni_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniUni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='-', max_length=255)),
                ('name', models.CharField(default='-', max_length=255)),
                ('uni', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
